name: gold
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #common libs
  #----------------
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^5.0.2
  cached_network_image: ^3.2.1
  auto_route: ^4.2.1
  get_it: ^7.2.0
  dio: ^4.0.6
  path_provider: ^2.0.11
  image: ^3.2.0
  fluttertoast: ^8.0.8
  animated_splash_screen: ^1.3.0
  flutter_config: ^2.0.0
  intl: ^0.17.0
  formz: ^0.4.1
  package_info_plus: ^1.4.3
  device_info_plus: ^4.0.1
  images_picker: ^1.2.4
  pull_to_refresh: ^2.0.0
  equatable: ^2.0.3
  event_bus: ^2.0.0
  #----------------
  #end common libs
  font_awesome_flutter: ^10.1.0
  smooth_page_indicator: ^1.0.0+2
  expandable: ^5.0.1
  video_player: ^2.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  auto_route_generator: ^4.2.0
  build_runner: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900